In [6]:
import pandas as pd
import seaborn as sns
import numpy as np

In [7]:
df = pd.read_csv('/content/drive/MyDrive/datasets/final_data_mice_protine.csv')

In [8]:
X = df.drop(['class'],axis=1)
y = df['class']


In [10]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler()
X[:] = scaler.fit_transform(X[:])

normalizer = preprocessing.Normalizer()
X[:] = normalizer.fit_transform(X[:])

min_max_scaler = preprocessing.MinMaxScaler()
X[:] = min_max_scaler.fit_transform(X[:])


In [5]:
X

DYRK1A_N   ITSN1_N    BDNF_N  ...    Ts65Dn    Saline       S/C
0     0.324339  0.400112  0.877126  ...  0.196058  0.195952  0.214656
1     0.342015  0.363496  0.857200  ...  0.166012  0.165902  0.181760
2     0.334743  0.395036  0.868378  ...  0.174579  0.174471  0.191140
3     0.279753  0.303111  0.707963  ...  0.112141  0.112024  0.122779
4     0.272367  0.303483  0.714082  ...  0.100962  0.100845  0.110540
...        ...       ...       ...  ...       ...       ...       ...
1075  0.133144  0.195042  0.373880  ...  0.689149  0.689108  0.711946
1076  0.140490  0.197504  0.355722  ...  0.701689  0.701649  0.723566
1077  0.143022  0.178002  0.363346  ...  0.638695  0.638648  0.665193
1078  0.140459  0.189794  0.387792  ...  0.635509  0.635461  0.662240
1079  0.176883  0.202366  0.392946  ...  0.668141  0.668098  0.692479

[1080 rows x 80 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=100)

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_test,y_pred)
score = accuracy_score(y_test,y_pred)
print(cm)
print(score)

[[43  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0]
 [ 0  0 59  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0]
 [ 0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0 27  0  0]
 [ 0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0  0  0 47]]
1.0


In [15]:
from sklearn.model_selection import RandomizedSearchCV

In [16]:
#Randomized Search CV

# Number of trees in Xgboost
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 200, num = 8)]
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(1, 10, num = 3)]
min_samples_split = [2, 5, 10, 15]
min_samples_leaf = [1, 2, 5] 

In [17]:
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_depth': max_depth,
               'min_samples_leaf':min_samples_leaf,
              'min_samples_split':min_samples_split}

print(random_grid)

{'n_estimators': [10, 37, 64, 91, 118, 145, 172, 200], 'max_depth': [1, 5, 10], 'min_samples_leaf': [1, 2, 5], 'min_samples_split': [2, 5, 10, 15]}


In [18]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
classifier=RandomForestClassifier()

In [ ]:
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations
rf_random = RandomizedSearchCV(estimator = classifier, param_distributions = random_grid,scoring='accuracy', n_iter =51, cv = 5, verbose=2, random_state=42, n_jobs = -1)

In [ ]:
rf_random.fit(X_train,y_train)

Fitting 5 folds for each of 51 candidates, totalling 255 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:    6.4s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:   29.0s
[Parallel(n_jobs=-1)]: Done 255 out of 255 | elapsed:   54.8s finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [ ]:
rf_random.best_params_


{'max_depth': 5,
 'min_samples_leaf': 2,
 'min_samples_split': 15,
 'n_estimators': 145}

In [ ]:
y_pred_ht = rf_random.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(cm)
print(score)

[[43  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0]
 [ 0  0 59  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0]
 [ 0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0 27  0  0]
 [ 0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0  0  0 47]]
1.0
